version: '3.8'

services:
  darkoperator:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DARKOPERATOR_ENV=development
      - DARKOPERATOR_LOG_LEVEL=INFO
    volumes:
      - ./data:/app/data
      - ./results:/app/results
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: darkoperator
      POSTGRES_USER: darkoperator
      POSTGRES_PASSWORD: darkoperator
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
