name: darkoperator
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - numpy=1.24.*
  - scipy=1.10.*
  - matplotlib=3.7.*
  - pandas=2.0.*
  - scikit-learn=1.3.*
  - h5py=3.9.*
  - tqdm=4.65.*
  - pyyaml=6.0.*
  - requests=2.31.*
  - jupyter=1.0.*
  - notebook=6.5.*
  - plotly=5.15.*
  - dash=2.11.*
  
  # PyTorch ecosystem
  - pytorch=2.0.*
  - torchvision=0.15.*
  - pytorch-cuda=11.8
  
  # HEP-specific packages
  - uproot=5.0.*
  - awkward=2.3.*
  - particle=0.21.*
  
  # Development tools
  - pytest=7.4.*
  - pytest-cov=4.1.*
  - black=23.7.*
  - flake8=6.0.*
  - mypy=1.5.*
  
  # Optional ROOT (commented out as it can be complex to install)
  # - root=6.28.*
  
  - pip
  - pip:
    - hepstats>=0.6.0
    - pylhe>=0.3.0