alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093
global:
  evaluation_interval: 15s
  scrape_interval: 15s
scrape_configs:
- job_name: darkoperator-api
  metrics_path: /metrics
  scrape_interval: 10s
  static_configs:
  - targets:
    - localhost:8000
