apiVersion: apps/v1
kind: Deployment
metadata:
  name: darkoperator
  namespace: darkoperator
  labels:
    app: darkoperator
spec:
  replicas: 3
  selector:
    matchLabels:
      app: darkoperator
  template:
    metadata:
      labels:
        app: darkoperator
    spec:
      containers:
      - name: darkoperator
        image: darkoperator:latest
        ports:
        - containerPort: 8000
        env:
        - name: DARKOPERATOR_ENV
          value: "production"
        - name: DARKOPERATOR_WORKERS
          value: "4"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "8Gi"
            cpu: "4000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: darkoperator-service
  namespace: darkoperator
spec:
  selector:
    app: darkoperator
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer
---
apiVersion: v1
kind: Namespace
metadata:
  name: darkoperator
